version: "3.7"
services:
  app:
    build:
      args:
        user: pulodev
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: pulodev
    container_name: pulodev-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pulodev

  db:
    image: mysql:5.7
    container_name: pulodev-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/data:/var/lib/mysql
    networks:
      - pulodev

  nginx:
    image: nginx:alpine
    container_name: pulodev-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pulodev

networks:
  pulodev:
    driver: bridge